#!/bin/bash
File=/bin/xterm
echo -e "\032[41mReay to open the new terminal!\032[0m"
if [ ! -f $File ];then
echo -e "\033[41mThis shell command was not found and is being installed!\033[0m"
#arch: pacman -S xterm
pacman -S xterm
#Kali:apt-get install xterm -y 
else
	echo -e "\033[41mThis command exists ands writes to the configuration file!\033[0m"
fi
echo "Write to configuration file!"
#Non garbled character configuration file writing
cd /root
touch .Xresources
cat>.Xresources<<EOF
XTerm*faceNameDoublesize: Microsoft YaHei:antialias=True:pixelsize=14
xterm*foreground:rgb:b2/b2/b2
xterm*background:rgb:08/08/08
xterm*faceName: DejaVu Sans Mono:antialias=True:pixelsize=14
EOF
echo "Update configuration!!"
sleep 3s 
xrdb ~/.Xresources
echo "Start up terminal!"
xterm -T " update-terminal " -geometry 100x30 -e " pacman -Syyu 